#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -la"
alias l="ls -l"
alias la="ls -a"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -rf --"
alias t="tmux"
alias y="yarn"
alias fd="fdfind"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Git specific aliases
alias gg="git gui"
alias gst="git status"
alias gl="git log"

# Load OS specific aliases.

# . "aliases/ubuntu/bash_aliases"

alias open="gio open"

alias sbrc="source ~/.bashrc"
# Mount MiniStorage
#  alias mountministorage="sudo mount -t cifs //macmini.local/hdd /home/dsp/MiniStorage -o uid=dsp,gid=samba,credentials=/home/dsp/.smbcredentials,noexec"
